import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";


const montserrat = Montserrat({

  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montserrat.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children} 
          <Toaster /> 
        </Providers>
      </body>
    </html>
  );
}
